name: Sync Data from Gitee

on:
  schedule:
    # 每天北京时间凌晨 2 点 (18:00 UTC) 自动执行
    - cron: '0 13 * * *'
  workflow_dispatch:

jobs:
  sync-file:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout GitHub Repo
        uses: actions/checkout@v4

      - name: Download data file from Gitee
        run: |
          # 准备本地目录
          mkdir -p $(dirname "${{ secrets.GITEE_DATA_PATH }}")
          
          # 调用 Gitee API 并将 HTTP 状态码和响应体分开
          API_RESPONSE=$(curl -s -w "\n%{http_code}" -H "Authorization: token ${{ secrets.GITEE_TOKEN }}" \
            "https://gitee.com/api/v5/repos/${{ secrets.GITEE_REPO }}/contents/${{ secrets.GITEE_DATA_PATH }}")
          
          # 提取响应体和状态码
          BODY=$(echo "$API_RESPONSE" | sed '$d')
          HTTP_CODE=$(echo "$API_RESPONSE" | tail -n 1)

          # 打印日志用于调试
          echo "Gitee API HTTP Status Code: $HTTP_CODE"
          echo "Gitee API Response Body: $BODY"

          # 检查请求是否成功
          if [ "$HTTP_CODE" != "200" ]; then
            echo "Error: Gitee API returned status $HTTP_CODE. Please check your GITEE_TOKEN, GITEE_REPO, and GITEE_DATA_PATH secrets."
            exit 1
          fi
          
          # 从响应体中提取下载链接
          DOWNLOAD_URL=$(echo "$BODY" | jq -r '.download_url')
            
          # 检查是否成功提取到 URL
          if [ -z "$DOWNLOAD_URL" ] || [ "$DOWNLOAD_URL" == "null" ]; then
            echo "Error: Could not extract 'download_url' from Gitee API response."
            echo "This usually means the path in your secrets points to a directory, not a file."
            exit 1
          fi
          
          # 使用获取到的链接下载文件
          curl -s -L -o "${{ secrets.GITEE_DATA_PATH }}" "$DOWNLOAD_URL"
          echo "File downloaded successfully to ${{ secrets.GITEE_DATA_PATH }}"

      - name: Commit and push if changed
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "chore(data): Sync daily data from Gitee"
          file_pattern: "${{ secrets.GITEE_DATA_PATH }}"
          commit_user_name: github-actions[bot]
          commit_user_email: 41898282+github-actions[bot]@users.noreply.github.com
          commit_author: GitHub Actions <41898282+github-actions[bot]@users.noreply.github.com>
