name: Sync Data from Gitee

on:
  # 每天北京时间凌晨 2 点 (13:00 UTC) 自动执行
  schedule:
    - cron: '0 18 * * *'
  # 允许在 Actions 页面手动触发此工作流
  workflow_dispatch:

jobs:
  sync-file:
    runs-on: ubuntu-latest
    steps:
      # 1. Checkout 当前的 GitHub 仓库
      - name: Checkout GitHub Repo
        uses: actions/checkout@v4

      # 2. 直接从 Gitee 的 raw 链接下载文件
      - name: Download data file from Gitee
        run: |
          # 直接从 Gitee 的 raw URL 下载文件
          # 注意：这里假设文件在 master 分支，和您截图一致
          curl -s -L -o "${{ secrets.GITEE_DATA_PATH }}" \
            "https://gitee.com/${{ secrets.GITEE_REPO }}/raw/master/${{ secrets.GITEE_DATA_PATH }}"
          
          # 检查文件是否下载成功（检查文件大小是否大于0）
          if [ ! -s "${{ secrets.GITEE_DATA_PATH }}" ]; then
            echo "Error: Failed to download file from Gitee or the file is empty."
            echo "Please double check your secrets are set correctly:"
            echo "GITEE_REPO: Peter817/copper_record"
            echo "GITEE_DATA_PATH: copper_forex_daily.csv"
            exit 1
          fi
          
          echo "File downloaded successfully."

      # 3. 自动提交和推送文件（如果文件内容有变化）
      - name: Commit and push if changed
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "chore(data): Sync daily data from Gitee"
          file_pattern: "${{ secrets.GITEE_DATA_PATH }}"
          commit_user_name: github-actions[bot]
          commit_user_email: 41898282+github-actions[bot]@users.noreply.github.com
          commit_author: GitHub Actions <41898282+github-actions[bot]@users.noreply.github.com>
