name: Sync Data from Gitee

on:
  # 每天北京时间凌晨 2 点 (13:00 UTC) 自动执行
  schedule:
    - cron: '0 13 * * *'
  # 允许在 Actions 页面手动触发此工作流
  workflow_dispatch:

jobs:
  sync-file:
    runs-on: ubuntu-latest
    steps:
      # 1. Checkout 当前的 GitHub 仓库
      - name: Checkout GitHub Repo
        uses: actions/checkout@v4

      # 2. 下载文件，并增加详细的调试信息
      - name: Download data file from Gitee with Debugging
        run: |
          # 遇到错误立即退出，并打印出所有执行的命令
          set -ex

          # 定义变量，让命令更清晰
          FILE_PATH="${{ secrets.GITEE_DATA_PATH }}"
          DOWNLOAD_URL="https://gitee.com/${{ secrets.GITEE_REPO }}/raw/master/${FILE_PATH}"

          echo "--- Debug Info ---"
          echo "Downloading from URL: ${DOWNLOAD_URL}"
          echo "Saving to local path: ${FILE_PATH}"
          echo "------------------"

          # 使用 shell 重定向来写入文件
          curl -s -L "${DOWNLOAD_URL}" > "${FILE_PATH}"

          echo "Download command finished. Listing current directory contents:"
          ls -la

          # 再次检查文件是否下载成功且不为空
          if [ ! -s "${FILE_PATH}" ]; then
            echo "Error: File was not downloaded correctly or is empty."
            exit 1
          fi
          
          echo "File downloaded successfully."

      # 3. 自动提交和推送文件
      - name: Commit and push if changed
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "chore(data): Sync daily data from Gitee"
          file_pattern: "${{ secrets.GITEE_DATA_PATH }}"
          commit_user_name: github-actions[bot]
          commit_user_email: 41898282+github-actions[bot]@users.noreply.github.com
          commit_author: GitHub Actions <41898282+github-actions[bot]@users.noreply.github.com>
